/**
 * Ham ticket "Proje" adı → canonical (resmi) proje adı eşlemesi.
 *
 * Kaynak veride aynı müşteri onlarca varyantla geçiyor (büyük/küçük harf,
 * boşluk, ek: STOKBAR/QUEST, tam ticari unvan, typo): "Nestle" / "NESTLE
 * ENROUTE", "REDBULL" / "RED BULL", "Doğuş Çay" / "DOĞUŞÇAY" / "DOGUSCAY" …
 * Bu tablo hepsini tek resmi ada indirger (UNIPORT.dbo.TBLPROJE ile elle
 * mutabakat + manuel eşleştirme). Yalnız raw != canonical olan çiftler var;
 * haritada OLMAYAN projeler kendi adıyla kalır (gerçek müşteri, gizlenmez).
 * 'Diğer' = junk/test/iç kayıt/atanmamış (gerçek müşteri değil).
 *
 * Raporlarda Proje kırılımında kullanılır (monitoring pivot). Yeni varyant
 * çıkarsa buraya eklenir. NOT: tek yönlü, salt-veri; kod mantığı içermez.
 */
export const PROJE_MAP = {
  'ABC TEMİZLİK': 'ABC',
  'ALPEDO': 'Alpedo',
  'Altıparmak': 'Altıparmak - Balparmak',
  'BUNGE': 'Ana Gida Bunge',
  'ANADOLU MOTOR STOKBAR': 'Anadolu Motor',
  'Quest Arçelik Hitachi Thailand': 'Arçelik Hitachi',
  'ARMA İLAÇ': 'Arma İlaç',
  'AROMA': 'Aroma Içecek',
  'AYDEM': 'Aydem',
  'BELKIM': 'BELKİM',
  'Belkim': 'BELKİM',
  'BİLGİNOĞLU': 'Bilginoglu (Stokbar)',
  'BRISA STOKBAR': 'Brisa',
  'ÇAYKUR': 'Çaykur',
  'ÇAYTAŞ QUEST': 'ÇAYTAŞ',
  'DANONE TİKVEŞLİ': 'Danone Tikveşli',
  'DANONE WATERS': 'Danone Waters',
  'DEVA': 'Deva İçecek',
  'Avea': 'Diğer',
  'EMİNOĞLU MERMER STOKBAR': 'Diğer',
  'DATA ÖZEL EĞİTİM': 'Diğer',
  'AZTEK TEKNOLOJİ ÜRÜNLERİ LTD.ŞTİ.': 'Diğer',
  'P5388': 'Diğer',
  'TEST2': 'Diğer',
  '14732': 'Diğer',
  '***YOK***': 'Diğer',
  'NULL': 'Diğer',
  'ALDEMİR BİLİŞİM': 'Diğer',
  'MOPAK STOKBAR': 'Diğer',
  'P3993': 'Diğer',
  'WEBSİS YAZILIM VE BİLGİSAYAR HAYRİYE BEKTAŞ': 'Diğer',
  'JOHNSONWAX': 'Diğer',
  '0': 'Diğer',
  'GOLD HARVEST': 'Diğer',
  '(Atanmamış)': 'Diğer',
  'UNIVERA BİLGİSAYAR SİSTEMLERİ SANAYİ VE TİCARET A.Ş.': 'Diğer',
  'MATRİKS': 'Diğer',
  'TEST1': 'Diğer',
  'DOKUZ SİSTEM': 'Diğer',
  'varuna': 'Diğer',
  'TURKISH DO&CO STOKBAR': 'Diğer',
  'LEANK BUSİNESS': 'Diğer',
  'SCHNEIDER': 'Diğer',
  'Saha Veri Toplama Pilot': 'Diğer',
  'ABALIOĞLU SAMİ': 'Diğer',
  'MOY BİLGİSAYAR': 'Diğer',
  'DOĞADAN QUEST': 'Doğadan Quest',
  'SUZUKI': 'Doğan Trend(Suzuki)',
  'SUZUKİ': 'Doğan Trend(Suzuki)',
  'DOĞANAY': 'Doğanay Gıda',
  'DOGUSCAY': 'Doğuşçay',
  'Doğuş Çay': 'Doğuşçay',
  'DOĞUŞÇAY': 'Doğuşçay',
  'DOĞUŞ ÇAY STOKBAR': 'Doğuşçay STOKBAR',
  'Düzey Pazarlama': 'Düzey',
  'Intema': 'Eczacibasi Intema',
  'EFES BELARUS': 'Efes Belarus',
  'EFES KAZAKHSTAN': 'Efes Kazakhstan',
  'EFES MOLDOVA': 'Efes Moldova',
  'Anadolu Efes': 'Efes Pilsen-Türkiye',
  'ERUSLU': 'Eruslu Sağlık',
  'EZEL KOZMETİK (DERMOKİL)': 'Ezel Kozmetik (Dermokil)',
  'GSK': 'GlaxoSmithKline (GSK)',
  'HARİBO': 'Haribo',
  'HARIBO ŞEKERLEME SAN. TİC.LTD. ŞTİ.': 'Haribo',
  'HAYAT KİMYA': 'Hayat Kimya',
  'HENKEL': 'Henkel',
  'Hobi': 'Hobi Kozmetik & Ra Pazarlama',
  'JTI QUEST_MERCH': 'JTI',
  'JTI İRAN': 'JTI İran',
  'Kebir': 'Kebir Süt',
  'Kent': 'Kent (Mondelez)',
  'KENT QUEST': 'Kent Merch',
  'KOPAŞ': 'Kopaş',
  'ANELE (KÜRESEL)': 'Küresel Netlog Anele',
  'KÜRESEL TEDARİK (NETLOG)': 'Küresel Tedarik (Netlog)',
  'LEVENT KİMYA': 'Levent Kimya',
  'MARS QUEST MERCH': 'Mars Quest',
  'Menderes Home Stokbar': 'Menderes',
  'MENDERES': 'Menderes',
  'MEY İÇKİ QUEST MERCH': 'Mey Quest',
  'MEY İÇKİ': 'Mey-Diageo',
  'MURR ELEKTRONİK': 'MURR',
  'NESTLE FOOD': 'Nestle Food Profesyonel',
  'NESTLE PROF QUEST': 'Nestle Food Profesyonel',
  'NESTLE PROFESYONEL': 'Nestle Food Profesyonel',
  'NESTLE RETAIL STOKBAR': 'Nestle Retail',
  'NESTLE ENROUTE': 'Nestle Retail',
  'Nestle': 'Nestle Retail',
  'NESTLE QUEST': 'Nestle Retail',
  'NESTLE RETAİL': 'Nestle Retail',
  'NESTLE ROM STOKBAR': 'Nestle ROM',
  'Nestle Waters(Erikli)': 'Nestle Waters Erikli',
  'NEWAL': 'Newal',
  'NUROL MAKİNA': 'Nurol Makina',
  'JDE & OFÇAY': 'Ofçay - EFOR',
  'JDE OF ÇAY': 'Ofçay - EFOR',
  'Opet': 'OPET FUCHS',
  'OPET STOKBAR': 'OPET FUCHS',
  'OYAK QUEST': 'OYAK',
  'ÖZGÖRKEY STOKBAR': 'Özgörkey Stokbar',
  'PERNOD RİCARD': 'Pernod Ricard',
  'PERRIGO': 'Perrigo',
  'Benckiser': 'Reckitt Benckiser',
  'REDBULL': 'RedBull',
  'RED BULL': 'RedBull',
  'ROYAL CANIN': 'Royal Canin',
  'Girişim': 'Sanipak Bos (Eczacıbaşı Girişim)',
  'EPSİS SANIPAK': 'Sanipak Epsis (Eczacıbaşı Profesyonel)',
  'Eczacıbaşı Profesyonel': 'Sanipak Epsis (Eczacıbaşı Profesyonel)',
  'BEYLERBEYİ': 'Sarper İçecek - Beylerbeyi',
  'SBR STOKBAR': 'SBR',
  'SÜTAŞ A.Ş.-ESY': 'Sütaş ESY',
  'SÜTAŞ - MONO DISTRUBUTOR': 'Sütaş Mono Distribütör',
  'Şen Piliç': 'Şenpiliç',
  'ŞENPİLİÇ': 'Şenpiliç',
  'ŞÖLEN': 'Şölen',
  'ŞÖLEN IRAK': 'Şölen Irak',
  'TADIM QUEST': 'Tadım',
  'TADIM': 'Tadım',
  'TAVUK DÜNYASI STOKBAR': 'Tavuk Dünyası (Stokbar)',
  'TORKU STOKBAR': 'TORKU',
  'TPI STOKBAR': 'TPI',
  'TRAKYA CAM': 'Trakya Cam',
  'TURKUAZ TRADE LLC-KIRGIZİSTAN': 'Turkuaz CAT Central Asia',
  'TURKTAB': 'TürkTab - EU Tobacco',
  'ULUDAĞ': 'Uludağ İçecek',
  'UNILEVER STOKBAR-İRAN': 'Unilever',
  'VİLEDA QUEST': 'Vileda - Hedef Ajans',
  'VODAFONE': 'Vodafone',
  'VODAFONE KKTC': 'Vodafone KKTC',
  'WAGNER STOKBAR': 'Wagner',
  'Weitnauer': 'Weitnauer Türkiye',
  'WEITNAUER': 'Weitnauer Türkiye',
};
