ALTER TABLE [Case] ADD CONSTRAINT [CK_Case_aiPriorityPrediction] CHECK ([aiPriorityPrediction]=N'Critical' OR [aiPriorityPrediction]=N'High' OR [aiPriorityPrediction]=N'Medium' OR [aiPriorityPrediction]=N'Low');
ALTER TABLE [Case] ADD CONSTRAINT [CK_Case_approvalState] CHECK ([approvalState]=N'Cancelled' OR [approvalState]=N'Rejected' OR [approvalState]=N'Approved' OR [approvalState]=N'Pending');
ALTER TABLE [Case] ADD CONSTRAINT [CK_Case_caseType] CHECK ([caseType]=N'Churn' OR [caseType]=N'ProactiveTracking' OR [caseType]=N'GeneralSupport');
ALTER TABLE [Case] ADD CONSTRAINT [CK_Case_escalationLevel] CHECK ([escalationLevel]=N'UstYonetim' OR [escalationLevel]=N'Direktor' OR [escalationLevel]=N'TakimLideri' OR [escalationLevel]=N'Yok');
ALTER TABLE [Case] ADD CONSTRAINT [CK_Case_origin] CHECK ([origin]=N'Diger' OR [origin]=N'Chatbot' OR [origin]=N'Web' OR [origin]=N'Eposta' OR [origin]=N'Telefon');
ALTER TABLE [Case] ADD CONSTRAINT [CK_Case_priority] CHECK ([priority]=N'Critical' OR [priority]=N'High' OR [priority]=N'Medium' OR [priority]=N'Low');
ALTER TABLE [Case] ADD CONSTRAINT [CK_Case_requestType] CHECK ([requestType]=N'Hata' OR [requestType]=N'Sikayet' OR [requestType]=N'Talep' OR [requestType]=N'Oneri' OR [requestType]=N'Bilgi');
ALTER TABLE [Case] ADD CONSTRAINT [CK_Case_snoozePreviousStatus] CHECK ([snoozePreviousStatus]=N'IptalEdildi' OR [snoozePreviousStatus]=N'YenidenAcildi' OR [snoozePreviousStatus]=N'Cozuldu' OR [snoozePreviousStatus]=N'Eskalasyon' OR [snoozePreviousStatus]=N'ThirdPartyWaiting' OR [snoozePreviousStatus]=N'Incelemede' OR [snoozePreviousStatus]=N'Acik');
ALTER TABLE [Case] ADD CONSTRAINT [CK_Case_status] CHECK ([status]=N'IptalEdildi' OR [status]=N'YenidenAcildi' OR [status]=N'Cozuldu' OR [status]=N'Eskalasyon' OR [status]=N'ThirdPartyWaiting' OR [status]=N'Incelemede' OR [status]=N'Acik');
ALTER TABLE [Case] ADD CONSTRAINT [CK_Case_supportLevel] CHECK ([supportLevel]=N'Expert' OR [supportLevel]=N'L3' OR [supportLevel]=N'L2' OR [supportLevel]=N'L1');
ALTER TABLE [CaseResolutionApproval] ADD CONSTRAINT [CK_CaseResolutionApproval_state] CHECK ([state]=N'Cancelled' OR [state]=N'Rejected' OR [state]=N'Approved' OR [state]=N'Pending');
ALTER TABLE [FieldDefinition] ADD CONSTRAINT [CK_FieldDefinition_caseType] CHECK ([caseType]=N'Churn' OR [caseType]=N'ProactiveTracking' OR [caseType]=N'GeneralSupport');
ALTER TABLE [Package] ADD CONSTRAINT [CK_Package_supportLevel] CHECK ([supportLevel]=N'Expert' OR [supportLevel]=N'L3' OR [supportLevel]=N'L2' OR [supportLevel]=N'L1');
ALTER TABLE [Person] ADD CONSTRAINT [CK_Person_supportLevel] CHECK ([supportLevel]=N'Expert' OR [supportLevel]=N'L3' OR [supportLevel]=N'L2' OR [supportLevel]=N'L1');
ALTER TABLE [Product] ADD CONSTRAINT [CK_Product_supportLevel] CHECK ([supportLevel]=N'Expert' OR [supportLevel]=N'L3' OR [supportLevel]=N'L2' OR [supportLevel]=N'L1');
ALTER TABLE [SLAPolicy] ADD CONSTRAINT [CK_SLAPolicy_requestType] CHECK ([requestType]=N'Hata' OR [requestType]=N'Sikayet' OR [requestType]=N'Talep' OR [requestType]=N'Oneri' OR [requestType]=N'Bilgi');
ALTER TABLE [Team] ADD CONSTRAINT [CK_Team_defaultSupportLevel] CHECK ([defaultSupportLevel]=N'Expert' OR [defaultSupportLevel]=N'L3' OR [defaultSupportLevel]=N'L2' OR [defaultSupportLevel]=N'L1');
ALTER TABLE [User] ADD CONSTRAINT [CK_User_role] CHECK ([role]=N'SystemAdmin' OR [role]=N'Admin' OR [role]=N'CSM' OR [role]=N'Supervisor' OR [role]=N'Backoffice' OR [role]=N'Agent');
ALTER TABLE [UserCompany] ADD CONSTRAINT [CK_UserCompany_role] CHECK ([role]=N'SystemAdmin' OR [role]=N'Admin' OR [role]=N'Supervisor' OR [role]=N'Agent');
